

trigger:
- master

resources:
- repo: self


variables:
  ImageName: 'lidorlg/sample-app-python:latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(ImageName)'
        command: 'build'
        DockerFile: '**/Dockerfile'
       
        
      displayName: 'Build the Docker image'
    - task: Docker@2      
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(ImageName)'
        command: 'push'
        
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      displayName: 'Push the Docker image to Dockerhub'



