name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
 
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: run & test Container
      run: docker run -itd --name python-hello -p 8080   my-image-name:latest
    - run: curl localhost:8080
   

#  Test:
#    needs: Build
#    runs-on: ubuntu-latest
#    steps:
   # 
#    - name: run & test Container
#      run: docker run -itd --name python-hello -p 8080   my-image-name:latest
 
  
 
    
