name: CI-Python
on:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install requirments
      run: pip install -r requirements.txt
    - name: run & test the container
      run: python app.py && sleep 5 && curl localhost:8080
      
    
      
